app/accounts/urls.py
from django.urls import path
from accounts import views


app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('activate/<uuid:username>/', views.UserActivateView.as_view(), name='user_activate'),
    path('my_profile/', views.UserProfileView.as_view(), name='my_profile'),
]

app/currency/urls.py
from django.urls import path
from currency import views


app_name = 'currency'

urlpatterns = [
    path('rate/generator/', views.rate_generator, name='rate_generator'),
    path('contactus/generator/', views.contactus_generator, name='contactus_generator'),

    path('', views.IndexView.as_view(), name='index'),

    path('source/list/', views.SourceListView.as_view(), name='source_list'),
    path('source/create/', views.SourceCreateView.as_view(), name='source_create'),
    path('source/update/<int:pk>', views.SourceUpdateView.as_view(), name='source_update'),
    path('source/delete/<int:pk>', views.SourceDeleteView.as_view(), name='source_delete'),
    path('source/details/<int:pk>', views.SourceDetailsView.as_view(), name='source_details'),

    path('rate/list/', views.RateListView.as_view(), name='rate_list'),
    path('rate/create/', views.RateCreateView.as_view(), name='rate_create'),
    path('rate/update/<int:pk>', views.RateUpdateView.as_view(), name='rate_update'),
    path('rate/delete/<int:pk>', views.RateDeleteView.as_view(), name='rate_delete'),
    path('rate/details/<int:pk>', views.RateDetailsView.as_view(), name='rate_details'),
    path('rate/download/', views.DownloadRateView.as_view(), name='rate_download'),

    # path('contactus/list/', views.ContactUsListView.as_view(), name='contactus_list'),
    path('contactus/create/', views.ContactUsCreateView.as_view(), name='contactus_create'),
    # path('contactus/update/<int:pk>', views.ContactUsUpdateView.as_view(), name='contactus_update'),
    # path('contactus/delete/<int:pk>', views.ContactUsDeleteView.as_view(), name='contactus_delete'),
    # path('contactus/details/<int:pk>', views.ContactUsDetailsView.as_view(), name='contactus_details'),

    path('ajax/', views.AjaxPartsPageView.as_view(), name='ajax_parts_page_view'),
    # path('ajax/ajax_get_value/', views.ajax_get_value, name='ajax_get_value'),
    # path('ajax/ajax_get_table_1/', views.ajax_get_table_1, name='ajax_get_table_1'),
    path('ajax/main_frame_content_get/', views.main_frame_content_get, name='main_frame_content_get'),
    path('ajax/sub_frame_content_get/', views.sub_frame_content_get, name='sub_frame_content_get'),
]

app/settings/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    path('currency/', include('currency.urls')),
    path('accounts/', include('accounts.urls')),
    path('api/v1/', include('api.v1.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('silk/', include('silk.urls', namespace='silk')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/currency/models.py
from django.db import models
from currency.model_choices import CarrencyType


class ResponseLog(models.Model):
    response_time = models.FloatField()
    request_method = models.CharField(max_length=10)
    path = models.CharField(max_length=200)
    query_params = models.CharField(max_length=500)
    ip = models.CharField(max_length=20)


def source_logo(instance, filename):
    return 'source_logo/{0}/{1}'.format(instance.id, filename)


class Source(models.Model):
    source_url = models.CharField(max_length=255)
    name = models.CharField(max_length=64, unique=True)
    code_name = models.CharField(max_length=16, unique=True)
    logo = models.FileField(upload_to=source_logo)

    def __str__(self):
        return self.name


class Rate(models.Model):

    # if field has choices, we can get choice value
    # python: get_base_currency_type_display()
    # template: get_base_currency_type_display
    base_currency_type = models.CharField(
        max_length=3,
        choices=CarrencyType.choices,
        default=CarrencyType.CURRENCY_TYPE_UAH
    )
    currency_type = models.CharField(max_length=3, choices=CarrencyType.choices)
    sale = models.DecimalField(max_digits=10, decimal_places=4)
    buy = models.DecimalField(max_digits=10, decimal_places=4)
    source = models.ForeignKey('currency.Source',
                               on_delete=models.CASCADE,
                               related_name='rates')
    created = models.DateTimeField(auto_now_add=True)


class ContactUs(models.Model):
    email_from = models.EmailField(max_length=30)
    email_to = models.EmailField(max_length=30)
    subject = models.CharField(max_length=100)
    message = models.CharField(max_length=3000)
    sended = models.DateTimeField(auto_now_add=True)

app/currency/forms.py
from django import forms
from currency.models import Rate, ContactUs, Source


class RateForm(forms.ModelForm):
    class Meta:
        model = Rate
        fields = (
            'base_currency_type',
            'currency_type',
            'sale',
            'buy',
            'source',
        )


class ContactUsForm(forms.ModelForm):
    class Meta:
        model = ContactUs
        fields = (
            'email_from',
            # 'email_to',
            'subject',
            'message',
        )
        widgets = {
            'subject': forms.Textarea(attrs={'cols': 100, 'rows': 2}),
            'message': forms.Textarea(attrs={'cols': 100, 'rows': 5}),
        }


class SourceForm(forms.ModelForm):
    class Meta:
        model = Source
        fields = (
            'source_url',
            'name',
            'logo',
        )

        widgets = {
            'logo': forms.FileInput(attrs={'class': 'form-control-file border'})
        }

app/currency/views.py
import csv
import io

from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.decorators.cache import cache_page
from django.utils.decorators import method_decorator

from silk.profiling.profiler import silk_profile
from django_filters.views import FilterView

from currency.filters import RateFilter
from currency.models import Rate, ContactUs, Source
from currency import utils
from currency.forms import RateForm, ContactUsForm, SourceForm
from currency.tasks import send_contact_us_email


@method_decorator(cache_page(10), name='dispatch')
class IndexView(generic.TemplateView):
    template_name = 'currency/index.html'

    # input point for all queries
    # def dispatch(self, request, *args, **kwargs):
    #     response = super().dispatch(request, *args, **kwargs)
    #     return response

    @silk_profile(name='IndexView: get_context_data')
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Latest exchange rates'
        context['last_rate_date'] = utils.get_last_rate_date()
        context['currency_types_list'] = utils.get_currency_types()
        sort_by_type = {
            'sale_asc': 'Sort by Sale (ASC)',
            'sale_desc': 'Sort by Sale (DESC)',
            'buy_asc': 'Sort by Buy (ASC)',
            'buy_desc': 'Sort by Buy (DESC)',
        }
        if self.request.GET:
            context['last_rate_list'] = utils.get_last_rate_list(self.request.GET['sort_params'])
            context['sort_by'] = sort_by_type.get(self.request.GET['sort_params'])
        else:
            context['last_rate_list'] = utils.get_last_rate_list()
            context['sort_by'] = sort_by_type.get('sale_asc')
        return context


@silk_profile(name='rate_generator')
def rate_generator(request):
    """
    function clear currency_rate table,
    generate random values and insert 100 records into currency_rate table
    :param
    none
    :return:
    link to rate_list
    """
    utils.rates_gen()
    return HttpResponseRedirect(reverse('currency:rate_list'))


@silk_profile(name='contactus_generator')
def contactus_generator(request):
    """
    function clear currency_contactus table,
    and insert records into currency_contactus table
    :param
    none
    :return:
    link to contactus_list
    """
    utils.contactus_gen()
    return HttpResponseRedirect(reverse('currency:contactus_list'))


# =================Source==================
class SourceListView(generic.ListView):
    queryset = Source.objects.all().order_by('name')
    template_name = 'currency/source_list.html'

    @silk_profile(name='SourceListView: get_context_data')
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Source list'
        return context


class SourceCreateView(generic.CreateView):
    queryset = Source.objects.all()
    template_name = 'currency/source_create.html'
    form_class = SourceForm
    success_url = reverse_lazy('currency:source_list')

    @silk_profile(name='SourceCreateView: get_context_data')
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Source create'
        return context


class SourceUpdateView(generic.UpdateView):
    queryset = Source.objects.all()
    template_name = 'currency/source_update.html'
    form_class = SourceForm
    success_url = reverse_lazy('currency:source_list')

    @silk_profile(name='SourceUpdateView: get_context_data')
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Source update'
        return context


class SourceDeleteView(generic.DeleteView):
    queryset = Source.objects.all()
    template_name = 'currency/source_delete.html'
    success_url = reverse_lazy('currency:source_list')

    @silk_profile(name='SourceDeleteView: get_context_data')
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Source delete'
        return context


class SourceDetailsView(generic.DetailView):
    queryset = Source.objects.all()
    template_name = 'currency/source_details.html'

    @silk_profile(name='SourceDetailsView: get_context_data')
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f'Source details (Id={self.object.id})'
        return context


# =================Rate===================
class RateListView(LoginRequiredMixin, FilterView):
    queryset = Rate.objects.all().select_related('source')
    filterset_class = RateFilter
    template_name = 'currency/rate_list.html'
    paginate_by = 10
    ordering = '-created'
    order_choices = {
        'created': 'Created (ASC)',
        '-created': 'Created (DESC)',
        'sale': 'Sale (ASC)',
        '-sale': 'Sale (DESC)',
        'buy': 'Buy (ASC)',
        '-buy': 'Buy (DESC)',
    }

    def get_ordering(self):
        if 'sort_by' in self.request.GET:
            ordering = self.request.GET['sort_by']
        else:
            ordering = self.ordering
        return ordering

    def get_paginate_by(self, queryset):
        if 'page_size' in self.request.GET:
            paginate_by = self.request.GET['page_size']
        else:
            paginate_by = self.paginate_by
        return paginate_by

    @silk_profile(name='RateListView: get_context_data')
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Rates history'

        if self.request.GET.get('page'):
            cur_page = int(self.request.GET['page'])
        else:
            cur_page = 1

        context['pagination_get_visible_range'] = utils.pagination_get_visible_range(
            self.queryset.count(),
            self.paginate_by,
            cur_page
        )
        context['page_size'] = self.get_paginate_by(self.queryset)
        context['sort_by'] = self.get_ordering()
        context['order_by_show'] = self.order_choices.get(self.get_ordering())
        context['order_choices'] = self.order_choices

        filter_params = self.request.GET.copy()
        if self.page_kwarg in filter_params:
            del filter_params[self.page_kwarg]

        if 'page_size' in filter_params:
            del filter_params['page_size']

        if 'sort_by' in filter_params:
            del filter_params['sort_by']

        context['filter_params'] = filter_params.urlencode()
        context['filter_params_count'] = utils.filter_params_count(filter_params.dict())
        context['filtered'] = self.object_list.count()
        context['total'] = self.queryset.count()

        return context


class RateCreateView(generic.CreateView):
    queryset = Rate.objects.all()
    template_name = 'currency/rate_create.html'
    form_class = RateForm
    success_url = reverse_lazy('currency:rate_list')

    @silk_profile(name='RateCreateView: get_context_data')
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Rate create'
        return context


class RateUpdateView(UserPassesTestMixin, generic.UpdateView):
    queryset = Rate.objects.all()
    template_name = 'currency/rate_update.html'
    form_class = RateForm
    success_url = reverse_lazy('currency:rate_list')

    def test_func(self):
        """only allowed for superuser"""
        return self.request.user.is_superuser

    @silk_profile(name='RateUpdateView: get_context_data')
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Rate update'
        return context


class RateDeleteView(UserPassesTestMixin, generic.DeleteView):
    queryset = Rate.objects.all()
    template_name = 'currency/rate_delete.html'
    success_url = reverse_lazy('currency:rate_list')

    def test_func(self):
        """only allowed for superuser"""
        return self.request.user.is_superuser

    @silk_profile(name='RateDeleteView: get_context_data')
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Rate delete'
        return context


class RateDetailsView(generic.DetailView):
    queryset = Rate.objects.all()
    template_name = 'currency/rate_details.html'

    @silk_profile(name='RateDetailsView: get_context_data')
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f'Rate details (Id={self.object.id})'
        return context


class DownloadRateView(generic.View):
    """
    class for generating csv from Rate model
    """

    def get(self, request):
        """
        function based on io lib
        :param request:
        :return: csv
        """
        csv_io = io.StringIO()
        csv_writer = csv.writer(csv_io)
        headers = ['id', 'buy', 'sale']
        csv_writer.writerow(headers)
        for rate in Rate.objects.all():
            row = [
                rate.id,
                rate.buy,
                rate.sale,
            ]
            csv_writer.writerow(row)
        csv_io.seek(0)
        return HttpResponse(csv_io.read(), content_type='text/csv')


# =================ContactUs===================
# class ContactUsListView(generic.ListView):
#     queryset = ContactUs.objects.all()
#     template_name = 'contactus_list.html'

    # @silk_profile(name='ContactUsListView: get_context_data')
    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['title'] = 'Contact Us list'
    #     return context


class ContactUsCreateView(generic.CreateView):
    queryset = ContactUs.objects.all()

app/currency/templates/contactus_create.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block main_content %}
    <form method="post" class="needs-validation" novalidate>
        {% csrf_token %}
        {{ form|crispy }}
        <button type=submit class="btn btn-success">Send mail</button>
    </form>
{% endblock main_content %}

app/currency/templates/contactus_list.html
{% extends 'base.html' %}

{% block main_content %}
    <a class="custom_button" href="{% url 'currency:contactus_create' %}">Create ContactUs</a>
    {% if contactus_list %}
        <table>
        <caption>
            <strong>Список отправленных писем (всего: {{ contactus_list.count }} записей)</strong>
        </caption>
          <tr>
              <th>Id</th>
              <th>base_currency_type</th>
              <th>currency_type</th>
              <th>sale</th>
              <th>buy</th>
              <th>source</th>
              <th>created</th>
              <th colspan="3">actions</th>
          </tr>
          {% for contactus in contactus_list %}
          <tr>
              <td style="text-align: center;">{{ contactus.id }}</td>
              <td style="text-align: center;">{{ contactus.email_from }}</td>
              <td style="text-align: center;">{{ contactus.email_to }}</td>
              <td style="text-align: center;">{{ contactus.subject }}</td>
              <td style="text-align: center;">{{ contactus.message }}</td>
              <td style="text-align: center;">{{ contactus.sended|date:'Y-m-d H:i' }}</td>
              <td style="text-align: center;">
                  <a href="{% url 'currency:contactus_details' pk=contactus.id %}">Detail</a>
              </td>
              <td style="text-align: center;">
                  <a href="{% url 'currency:contactus_update' pk=contactus.id %}">Edit</a>
              </td>
              <td style="text-align: center;">
                  <a href="{% url 'currency:contactus_delete' pk=contactus.id %}">Delete</a>
              </td>
          </tr>
          {% endfor %}
        </table>

    {% else %}
        <p>contactus_list пуст, нет записей для вывода!</p>p>

    {% endif %}
{% endblock main_content %}

app/currency/templates/index.html
{% extends 'base.html' %}

{% block main_content %}
    <div class="container-fluid mb-3 text-center">
        {% if currency_types_list %}
            {# sort choices #}
            <div class="d-flex flex-column flex-md-row p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
                <div class="btn-group">
                    <button type="button" class="btn btn-outline-primary dropdown-toggle" data-toggle="dropdown">
                        {{ sort_by }}
                    </button>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'currency:index' %}?sort_params=sale_asc">Sort by Sale (ASC)"</a>
                        <a class="dropdown-item" href="{% url 'currency:index' %}?sort_params=sale_desc">Sort by Sale (DESC)</a>
                        <a class="dropdown-item" href="{% url 'currency:index' %}?sort_params=buy_asc">Sort by Buy (ASC)</a>
                        <a class="dropdown-item" href="{% url 'currency:index' %}?sort_params=buy_desc">Sort by Buy (DESC)</a>
                    </div>
                </div>
            </div>
            {% for c_types in currency_types_list %}
                <div class="card mb-4 shadow-sm">
                    <h3 class="text-center">
                        1 {{ c_types.currency_type }} ({{ c_types.base_currency_type }})
                    </h3>
                    <table class="table table-striped table-hover">
                        <thead>
                            <tr class="text-center">
                                <th>Source</th>
                                <th>Sale</th>
                                <th>Buy</th>
                                <th>Created</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for rate in last_rate_list %}
                                {% if rate.currency_type == c_types.currency_type and rate.base_currency_type == c_types.base_currency_type %}
                                    <tr class="text-center">
                                        <td>{{ rate.source.name }}</td>
                                        <td>{{ rate.sale }}</td>
                                        <td>{{ rate.buy }}</td>
                                        <td>{{ rate.created|date:'Y-m-d H:i' }}</td>
                                    </tr>
                                {% endif %}
                            {% endfor %}
                        </tbody>
                    </table>
                </div><br>
            {% endfor %}
        {% else %}
            <p>Sorry, Rate list is empty!</p>
        {% endif %}
    </div>
 {% endblock main_content %}

app/currency/templates/rate_create.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block main_content %}
    <form method="post" class="needs-validation" novalidate>
        {% csrf_token %}
        {{ form|crispy }}
        <button type=submit class="btn btn-success">Create</button>
    </form>
{% endblock main_content %}

app/currency/templates/rate_delete.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block main_content %}
    <p>Delete object with Id = {{ object.id }} ?</p>
    <form method="post">
        {% csrf_token %}
        <button type=submit class="btn btn-success">Delete</button>
    </form>
{% endblock main_content %}

app/currency/templates/rate_details.html
{% extends 'base.html' %}

{% block main_content %}
    {% if object %}
        <table class="table table-bordered table-hover">
            <thead>
                <tr class="table-active">
                    <th>Property</th>
                    <th>Value</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Base currency type</td>
                    <td>{{ object.get_base_currency_type_display }}</td>
                </tr>
                <tr>
                    <td>Currency type</td>
                    <td>{{ object.get_currency_type_display }}</td>
                </tr>
                <tr>
                    <td>Sale</td>
                    <td>{{ object.sale }}</td>
                </tr>
                <tr>
                    <td>Buy</td>
                    <td>{{ object.buy }}</td>
                </tr>
                <tr>
                    <td>Source</td>
                    <td>{{ object.source.name }}</td>
                </tr>
                <tr>
                    <td>Created</td>
                    <td>{{ object.created|date:'Y-m-d H:i' }}</td>
                </tr>
            </tbody>
        </table>
        <div>
            {% if request.user.is_superuser %}
                <a class="btn btn-success" href="{% url 'currency:rate_update' pk=object.id %}">Edit</a>
                <a class="btn btn-danger" href="{% url 'currency:rate_delete' pk=object.id %}">Delete</a>
            {% endif %}
        </div>
    {% else %}
        <p>Объект не найден!</p>p>
    {% endif %}
{% endblock main_content %}

app/currency/templates/rate_update.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block main_content %}
    <form method="post" class="needs-validation" novalidate>
        {% csrf_token %}
        {{ form|crispy }}
        <button type=submit class="btn btn-success">Update</button>
    </form>
{% endblock main_content %}

app/currency/templates/source_create.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block main_content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button type=submit class="btn btn-success">Create</button>
    </form>
{% endblock main_content %}

app/currency/templates/source_delete.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block main_content %}
    <p>Delete object with Id = {{ object.id }} ?</p>
    <form method="post">
        {% csrf_token %}
        <button type=submit class="btn btn-success">Delete</button>
    </form>
{% endblock main_content %}

app/currency/templates/source_details.html
{% extends 'base.html' %}

{% block main_content %}
    {% if object %}
        <table class="table table-bordered table-hover">
            <thead>
                <tr class="table-active">
                    <th>Property</th>
                    <th>Value</th>
                </tr>
            </thead>
            <tbody>

                <tr>
                    <td>Source logo</td>
                    <td>
                        <img src="{{ object.logo.url }}" height="100">
                    </td>
                </tr>
                <tr>
                    <td>Source url</td>
                    <td>
                        <a href="{{ source.source_url }}" target="_blank">{{ source.source_url }}</a>
                    </td>
                </tr>
                <tr>
                    <td>Name</td>
                    <td>{{ object.name }}</td>
                </tr>
            </tbody>
        </table>
        <div>
            {% if request.user.is_superuser %}
                <a class="btn btn-success" href="{% url 'currency:source_update' pk=object.id %}">Edit</a>
                <a class="btn btn-danger" href="{% url 'currency:source_delete' pk=object.id %}">Delete</a>
            {% endif %}
        </div>
    {% else %}
        <p>Объект не найден!</p>p>
    {% endif %}
{% endblock main_content %}

app/currency/templates/source_list.html
{% extends 'base.html' %}

{% block main_content %}

    <ul class="nav justify-content-end">
        <li class="nav-item">
            {% if request.user.is_superuser %}
            <a class="nav-link btn btn-outline-primary btn-sm" href="{% url 'currency:source_create' %}">
                Create Source
            </a>
            {% endif %}
        </li>
    </ul>

    {% if source_list %}
        <strong>Total: {{ source_list.count }}</strong>
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Logo</th>
                    <th>Name</th>
                    <th>Source url</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for source in source_list %}
                <tr>
                    <td>{{ source.id }}</td>
                    <td align="center">
                            {% if source.logo %}
                                <img src="{{ source.logo.url }}" height="25">
                            {% endif %}
                    </td>
                    <td>{{ source.name }}</td>
                    <td>
                        <a href="{{ source.source_url }}" target="_blank">{{ source.source_url }}</a>
                    </td>
                    <td>
                        <a href="{% url 'currency:source_details' pk=source.id %}">Details</a>
                        {% if request.user.is_superuser %}
                            <a href="{% url 'currency:source_update' pk=source.id %}">Edit</a>
                            <a href="{% url 'currency:source_delete' pk=source.id %}">Delete</a>
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

    {% else %}
        <p>Source list is empty!</p>

    {% endif %}
{% endblock main_content %}

app/currency/templates/source_update.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block main_content %}
    {% if object.logo %}
        <img src="{{ object.logo.url }}" height="100">
    {% endif %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button type=submit class="btn btn-success">Update</button>
    </form>
{% endblock main_content %}