app/accounts/urls.py
from django.urls import path
from accounts import views


app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('activate/<uuid:username>/', views.UserActivateView.as_view(), name='user_activate'),
    path('my_profile/', views.UserProfileView.as_view(), name='my_profile'),
]

app/currency/urls.py
from django.urls import path
from currency import views


app_name = 'currency'

urlpatterns = [
    path('rate/generator/', views.rate_generator, name='rate_generator'),
    path('contactus/generator/', views.contactus_generator, name='contactus_generator'),

    path('', views.IndexView.as_view(), name='index'),

    path('source/list/', views.SourceListView.as_view(), name='source_list'),
    path('source/create/', views.SourceCreateView.as_view(), name='source_create'),
    path('source/update/<int:pk>', views.SourceUpdateView.as_view(), name='source_update'),
    path('source/delete/<int:pk>', views.SourceDeleteView.as_view(), name='source_delete'),
    path('source/details/<int:pk>', views.SourceDetailsView.as_view(), name='source_details'),

    path('rate/list/', views.RateListView.as_view(), name='rate_list'),
    path('rate/create/', views.RateCreateView.as_view(), name='rate_create'),
    path('rate/update/<int:pk>', views.RateUpdateView.as_view(), name='rate_update'),
    path('rate/delete/<int:pk>', views.RateDeleteView.as_view(), name='rate_delete'),
    path('rate/details/<int:pk>', views.RateDetailsView.as_view(), name='rate_details'),
    path('rate/download/', views.DownloadRateView.as_view(), name='rate_download'),

    # path('contactus/list/', views.ContactUsListView.as_view(), name='contactus_list'),
    path('contactus/create/', views.ContactUsCreateView.as_view(), name='contactus_create'),
    # path('contactus/update/<int:pk>', views.ContactUsUpdateView.as_view(), name='contactus_update'),
    # path('contactus/delete/<int:pk>', views.ContactUsDeleteView.as_view(), name='contactus_delete'),
    # path('contactus/details/<int:pk>', views.ContactUsDetailsView.as_view(), name='contactus_details'),

    path('ajax/', views.AjaxPartsPageView.as_view(), name='ajax_parts_page_view'),
    # path('ajax/ajax_get_value/', views.ajax_get_value, name='ajax_get_value'),
    # path('ajax/ajax_get_table_1/', views.ajax_get_table_1, name='ajax_get_table_1'),
    path('ajax/main_frame_content_get/', views.main_frame_content_get, name='main_frame_content_get'),
    path('ajax/sub_frame_content_get/', views.sub_frame_content_get, name='sub_frame_content_get'),
]

app/settings/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    path('currency/', include('currency.urls')),
    path('accounts/', include('accounts.urls')),
    path('api/v1/', include('api.v1.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('silk/', include('silk.urls', namespace='silk')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/currency/models.py
from django.db import models
from currency.model_choices import CarrencyType


class ResponseLog(models.Model):
    response_time = models.FloatField()
    request_method = models.CharField(max_length=10)
    path = models.CharField(max_length=200)
    query_params = models.CharField(max_length=500)
    ip = models.CharField(max_length=20)


def source_logo(instance, filename):
    return 'source_logo/{0}/{1}'.format(instance.id, filename)


class Source(models.Model):
    source_url = models.CharField(max_length=255)
    name = models.CharField(max_length=64, unique=True)
    code_name = models.CharField(max_length=16, unique=True)
    logo = models.FileField(upload_to=source_logo)

    def __str__(self):
        return self.name


class Rate(models.Model):

    # if field has choices, we can get choice value
    # python: get_base_currency_type_display()
    # template: get_base_currency_type_display
    base_currency_type = models.CharField(
        max_length=3,
        choices=CarrencyType.choices,
        default=CarrencyType.CURRENCY_TYPE_UAH
    )
    currency_type = models.CharField(max_length=3, choices=CarrencyType.choices)
    sale = models.DecimalField(max_digits=10, decimal_places=4)
    buy = models.DecimalField(max_digits=10, decimal_places=4)
    source = models.ForeignKey('currency.Source',
                               on_delete=models.CASCADE,
                               related_name='rates')
    created = models.DateTimeField(auto_now_add=True)


class ContactUs(models.Model):
    email_from = models.EmailField(max_length=30)
    email_to = models.EmailField(max_length=30)
    subject = models.CharField(max_length=100)
    message = models.CharField(max_length=3000)
    sended = models.DateTimeField(auto_now_add=True)

app/currency/forms.py
from django import forms
from currency.models import Rate, ContactUs, Source


class RateForm(forms.ModelForm):
    class Meta:
        model = Rate
        fields = (
            'base_currency_type',
            'currency_type',
            'sale',
            'buy',
            'source',
        )


class ContactUsForm(forms.ModelForm):
    class Meta:
        model = ContactUs
        fields = (
            'email_from',
            # 'email_to',
            'subject',
            'message',
        )
        widgets = {
            'subject': forms.Textarea(attrs={'cols': 100, 'rows': 2}),
            'message': forms.Textarea(attrs={'cols': 100, 'rows': 5}),
        }


class SourceForm(forms.ModelForm):
    class Meta:
        model = Source
        fields = (
            'source_url',
            'name',
            'logo',
        )

        widgets = {
            'logo': forms.FileInput(attrs={'class': 'form-control-file border'})
        }

app/currency/views.py
import csv
import io

from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.decorators.cache import cache_page
from django.utils.decorators import method_decorator

from silk.profiling.profiler import silk_profile
from django_filters.views import FilterView

from currency.filters import RateFilter
from currency.models import Rate, ContactUs, Source
from currency import utils
from currency.forms import RateForm, ContactUsForm, SourceForm
from currency.tasks import send_contact_us_email


@method_decorator(cache_page(10), name='dispatch')
class IndexView(generic.TemplateView):
    template_name = 'currency/index.html'

    # input point for all queries
    # def dispatch(self, request, *args, **kwargs):
    #     response = super().dispatch(request, *args, **kwargs)
    #     return response

    @silk_profile(name='IndexView: get_context_data')
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Latest exchange rates'
        context['last_rate_date'] = utils.get_last_rate_date()
        context['currency_types_list'] = utils.get_currency_types()
        sort_by_type = {
            'sale_asc': 'Sort by Sale (ASC)',
            'sale_desc': 'Sort by Sale (DESC)',
            'buy_asc': 'Sort by Buy (ASC)',
            'buy_desc': 'Sort by Buy (DESC)',
        }
        if self.request.GET:
            context['last_rate_list'] = utils.get_last_rate_list(self.request.GET['sort_params'])
            context['sort_by'] = sort_by_type.get(self.request.GET['sort_params'])
        else:
            context['last_rate_list'] = utils.get_last_rate_list()
            context['sort_by'] = sort_by_type.get('sale_asc')
        return context


@silk_profile(name='rate_generator')
def rate_generator(request):
    """
    function clear currency_rate table,
    generate random values and insert 100 records into currency_rate table
    :param
    none
    :return:
    link to rate_list
    """
    utils.rates_gen()
    return HttpResponseRedirect(reverse('currency:rate_list'))


@silk_profile(name='contactus_generator')
def contactus_generator(request):
    """
    function clear currency_contactus table,
    and insert records into currency_contactus table
    :param
    none
    :return:
    link to contactus_list
    """
    utils.contactus_gen()
    return HttpResponseRedirect(reverse('currency:contactus_list'))


# =================Source==================
class SourceListView(generic.ListView):
    queryset = Source.objects.all().order_by('name')
    template_name = 'currency/source_list.html'

    @silk_profile(name='SourceListView: get_context_data')
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Source list'
        return context


class SourceCreateView(generic.CreateView):
    queryset = Source.objects.all()
    template_name = 'currency/source_create.html'
    form_class = SourceForm
    success_url = reverse_lazy('currency:source_list')

    @silk_profile(name='SourceCreateView: get_context_data')
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Source create'
        return context


class SourceUpdateView(generic.UpdateView):
    queryset = Source.objects.all()
    template_name = 'currency/source_update.html'
    form_class = SourceForm
    success_url = reverse_lazy('currency:source_list')

    @silk_profile(name='SourceUpdateView: get_context_data')
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Source update'
        return context


class SourceDeleteView(generic.DeleteView):
    queryset = Source.objects.all()
    template_name = 'currency/source_delete.html'
    success_url = reverse_lazy('currency:source_list')

    @silk_profile(name='SourceDeleteView: get_context_data')
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Source delete'
        return context


class SourceDetailsView(generic.DetailView):
    queryset = Source.objects.all()
    template_name = 'currency/source_details.html'

    @silk_profile(name='SourceDetailsView: get_context_data')
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f'Source details (Id={self.object.id})'
        return context


# =================Rate===================
class RateListView(LoginRequiredMixin, FilterView):
    queryset = Rate.objects.all().select_related('source')
    filterset_class = RateFilter
    template_name = 'currency/rate_list.html'
    paginate_by = 10
    ordering = '-created'
    order_choices = {
        'created': 'Created (ASC)',
        '-created': 'Created (DESC)',
        'sale': 'Sale (ASC)',
        '-sale': 'Sale (DESC)',
        'buy': 'Buy (ASC)',
        '-buy': 'Buy (DESC)',
    }

    def get_ordering(self):
        if 'sort_by' in self.request.GET:
            ordering = self.request.GET['sort_by']
        else:
            ordering = self.ordering
        return ordering

    def get_paginate_by(self, queryset):
        if 'page_size' in self.request.GET:
            paginate_by = self.request.GET['page_size']
        else:
            paginate_by = self.paginate_by
        return paginate_by

    @silk_profile(name='RateListView: get_context_data')
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Rates history'

        if self.request.GET.get('page'):
            cur_page = int(self.request.GET['page'])
        else:
            cur_page = 1

        context['pagination_get_visible_range'] = utils.pagination_get_visible_range(
            self.queryset.count(),
            self.paginate_by,
            cur_page
        )
        context['page_size'] = self.get_paginate_by(self.queryset)
        context['sort_by'] = self.get_ordering()
        context['order_by_show'] = self.order_choices.get(self.get_ordering())
        context['order_choices'] = self.order_choices

        filter_params = self.request.GET.copy()
        if self.page_kwarg in filter_params:
            del filter_params[self.page_kwarg]

        if 'page_size' in filter_params:
            del filter_params['page_size']

        if 'sort_by' in filter_params:
            del filter_params['sort_by']

        context['filter_params'] = filter_params.urlencode()
        context['filter_params_count'] = utils.filter_params_count(filter_params.dict())
        context['filtered'] = self.object_list.count()
        context['total'] = self.queryset.count()

        return context


class RateCreateView(generic.CreateView):
    queryset = Rate.objects.all()
    template_name = 'currency/rate_create.html'
    form_class = RateForm
    success_url = reverse_lazy('currency:rate_list')

    @silk_profile(name='RateCreateView: get_context_data')
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Rate create'
        return context


class RateUpdateView(UserPassesTestMixin, generic.UpdateView):
    queryset = Rate.objects.all()
    template_name = 'currency/rate_update.html'
    form_class = RateForm
    success_url = reverse_lazy('currency:rate_list')

    def test_func(self):
        """only allowed for superuser"""
        return self.request.user.is_superuser

    @silk_profile(name='RateUpdateView: get_context_data')
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Rate update'
        return context


class RateDeleteView(UserPassesTestMixin, generic.DeleteView):
    queryset = Rate.objects.all()
    template_name = 'currency/rate_delete.html'
    success_url = reverse_lazy('currency:rate_list')

    def test_func(self):
        """only allowed for superuser"""
        return self.request.user.is_superuser

    @silk_profile(name='RateDeleteView: get_context_data')
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Rate delete'
        return context


class RateDetailsView(generic.DetailView):
    queryset = Rate.objects.all()
    template_name = 'currency/rate_details.html'

    @silk_profile(name='RateDetailsView: get_context_data')
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f'Rate details (Id={self.object.id})'
        return context


class DownloadRateView(generic.View):
    """
    class for generating csv from Rate model
    """

    def get(self, request):
        """
        function based on io lib
        :param request:
        :return: csv
        """
        csv_io = io.StringIO()
        csv_writer = csv.writer(csv_io)
        headers = ['id', 'buy', 'sale']
        csv_writer.writerow(headers)
        for rate in Rate.objects.all():
            row = [
                rate.id,
                rate.buy,
                rate.sale,
            ]
            csv_writer.writerow(row)
        csv_io.seek(0)
        return HttpResponse(csv_io.read(), content_type='text/csv')


# =================ContactUs===================
# class ContactUsListView(generic.ListView):
#     queryset = ContactUs.objects.all()
#     template_name = 'contactus_list.html'

    # @silk_profile(name='ContactUsListView: get_context_data')
    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['title'] = 'Contact Us list'
    #     return context


class ContactUsCreateView(generic.CreateView):
    queryset = ContactUs.objects.all()

app/currency/templates/currency/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>{{ title }}</title>

        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
              rel="stylesheet"
              integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N"
              crossorigin="anonymous">
    </head>

    <body>
        {% load static %}

        {# NAVBAR #}
        <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3
                    fixed-top bg-white border-bottom shadow-sm">
            <a href="{% url 'currency:index' %}">
                <img src="{% static "img/currency_exchange.jpg" %}"
                     alt=""
                     style="margin-left: 20px; margin-right: 3px;"
                     height="44">
            </a>
            <h4 class="my-0 mr-md-auto font-weight-normal" style="padding-left: 10px;">
                Currency Exchange Project
            </h4>

            <nav class="my-2 my-md-0 mr-md-3">
                <a class="p-2 text-dark" href="{% url 'currency:index' %}">Latest rates</a>
                <a class="p-2 text-dark" href="{% url 'currency:rate_list' %}">Rates history</a>
                <a class="p-2 text-dark" href="{% url 'currency:source_list' %}">Sources</a>
                <a class="p-2 text-dark" href="{% url 'currency:contactus_create' %}">Contact Us</a>
            </nav>
            {% if request.user.is_authenticated %}
                {% if request.user.avatar %}
                    <img src="{{ request.user.avatar.url }}"
                         alt=""
                         style="margin-left: 20px; margin-right: 3px;"
                         width="44"
                         height="44">
                {% endif %}
                <a class="btn btn-outline-info"
                   style="margin-right: 3px;"
                   href="{% url 'accounts:my_profile' %}">{{ request.user.email }}</a>
                <a class="btn btn-outline-warning"
                   style="margin-right: 30px;"
                   href="{% url 'logout' %}">LogOut</a>
            {% else %}
                <a class="btn btn-outline-success"
                   style="margin-right: 3px;"
                   href="{% url 'login' %}">LogIn</a>
                <a class="btn btn-outline-warning"
                   style="margin-right: 30px;"
                   href="{% url 'accounts:signup' %}">SignUp</a>
            {% endif %}
        </div>

        {# MAIN #}
        <main role="main" class="container" style="padding-top: 40px;">
            {# HEADER #}
            <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
                <h4 class="display-5">{{ title }}</h4>
            </div>

            {# CONTENT #}
            <div class="container mx-auto">
            {% block main_content %}
            {% endblock main_content %}
            </div>

            {# FOOTER #}
            <footer class="pt-4 my-md-5 pt-md-5 border-top">
                <div class="row">
                    <div class="col-12 col-md">
                        <img class="mb-2"
                             src="{% static "img/hillel_logo.jpeg" %}"
                             alt=""
                             height="60">
                        <small class="d-block mb-3 text-muted">© 2022</small>
                    </div>
                    <div class="col-6 col-md">
                        <h5>Features</h5>
                        <ul class="list-unstyled text-small">
                            <li><a class="text-muted" href="#">Cool stuff</a></li>
                            <li><a class="text-muted" href="#">Random feature</a></li>
                            <li><a class="text-muted" href="#">Team feature</a></li>
                            <li><a class="text-muted" href="#">Stuff for developers</a></li>
                            <li><a class="text-muted" href="#">Another one</a></li>
                            <li><a class="text-muted" href="#">Last time</a></li>
                        </ul>
                    </div>
                    <div class="col-6 col-md">
                        <h5>Resources</h5>
                        <ul class="list-unstyled text-small">
                            <li><a class="text-muted" href="#">Resource</a></li>
                            <li><a class="text-muted" href="#">Resource name</a></li>
                            <li><a class="text-muted" href="#">Another resource</a></li>
                            <li><a class="text-muted" href="#">Final resource</a></li>
                        </ul>
                    </div>
                    <div class="col-6 col-md">
                        <h5>About</h5>
                        <ul class="list-unstyled text-small">
                            <li><a class="text-muted" href="#">Team</a></li>
                            <li><a class="text-muted" href="#">Locations</a></li>
                            <li><a class="text-muted" href="#">Privacy</a></li>
                            <li><a class="text-muted" href="#">Terms</a></li>
                        </ul>
                    </div>
                </div>
            </footer>
        </main>

{#        <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"#}
{#                integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"#}
{#                crossorigin="anonymous">#}
{#        </script>#}
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
        </script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"
                integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct"
                crossorigin="anonymous">
        </script>
    </body>
    {# <script src={% static "main/script.js"></script> %}> #}
    {% block add_script %}{% endblock %}
</html>

app/currency/templates/currency/contactus_create.html
{% extends 'currency/base.html' %}
{% load crispy_forms_filters %}

{% block main_content %}
    <form method="post" class="needs-validation" novalidate>
        {% csrf_token %}
        {{ form|crispy }}
        <button type=submit class="btn btn-success">Send mail</button>
    </form>
{% endblock main_content %}

app/currency/templates/currency/contactus_list.html
{% extends 'currency/base.html' %}

{% block main_content %}
    <a class="custom_button" href="{% url 'currency:contactus_create' %}">Create ContactUs</a>
    {% if contactus_list %}
        <table>
        <caption>
            <strong>Список отправленных писем (всего: {{ contactus_list.count }} записей)</strong>
        </caption>
          <tr>
              <th>Id</th>
              <th>base_currency_type</th>
              <th>currency_type</th>
              <th>sale</th>
              <th>buy</th>
              <th>source</th>
              <th>created</th>
              <th colspan="3">actions</th>
          </tr>
          {% for contactus in contactus_list %}
          <tr>
              <td style="text-align: center;">{{ contactus.id }}</td>
              <td style="text-align: center;">{{ contactus.email_from }}</td>
              <td style="text-align: center;">{{ contactus.email_to }}</td>
              <td style="text-align: center;">{{ contactus.subject }}</td>
              <td style="text-align: center;">{{ contactus.message }}</td>
              <td style="text-align: center;">{{ contactus.sended|date:'Y-m-d H:i' }}</td>
              <td style="text-align: center;">
                  <a href="{% url 'currency:contactus_details' pk=contactus.id %}">Detail</a>
              </td>
              <td style="text-align: center;">
                  <a href="{% url 'currency:contactus_update' pk=contactus.id %}">Edit</a>
              </td>
              <td style="text-align: center;">
                  <a href="{% url 'currency:contactus_delete' pk=contactus.id %}">Delete</a>
              </td>
          </tr>
          {% endfor %}
        </table>

    {% else %}
        <p>contactus_list пуст, нет записей для вывода!</p>p>

    {% endif %}
{% endblock main_content %}

app/currency/templates/currency/rate_details.html
{% extends 'currency/base.html' %}

{% block main_content %}
    {% if object %}
        <table class="table table-bordered table-hover">
            <thead>
                <tr class="table-active">
                    <th>Property</th>
                    <th>Value</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Base currency type</td>
                    <td>{{ object.get_base_currency_type_display }}</td>
                </tr>
                <tr>
                    <td>Currency type</td>
                    <td>{{ object.get_currency_type_display }}</td>
                </tr>
                <tr>
                    <td>Sale</td>
                    <td>{{ object.sale }}</td>
                </tr>
                <tr>
                    <td>Buy</td>
                    <td>{{ object.buy }}</td>
                </tr>
                <tr>
                    <td>Source</td>
                    <td>{{ object.source.name }}</td>
                </tr>
                <tr>
                    <td>Created</td>
                    <td>{{ object.created|date:'Y-m-d H:i' }}</td>
                </tr>
            </tbody>
        </table>
        <div>
            {% if request.user.is_superuser %}
                <a class="btn btn-success" href="{% url 'currency:rate_update' pk=object.id %}">Edit</a>
                <a class="btn btn-danger" href="{% url 'currency:rate_delete' pk=object.id %}">Delete</a>
            {% endif %}
        </div>
    {% else %}
        <p>Объект не найден!</p>p>
    {% endif %}
{% endblock main_content %}

app/currency/templates/currency/rate_list.html
{% extends 'currency/base.html' %}
{% load crispy_forms_filters %}

{% block main_content %}

    <ul class="nav justify-content-end">
        <li class="nav-item">
            <div class="container" style="border-style: inherit;">
                <button type="button" class="btn btn-outline-primary" data-toggle="collapse" data-target="#filters-area">
                    Filters <span class="badge badge-primary">{{ filter_params_count }}</span>
                </button>
                <div id="filters-area" class="collapse">
                    {# filters form #}
                    <form method="get">
                        {{ filter.form|crispy }}
                        <div class="button-group">
                            <button type="submit" class="btn btn-outline-success">Apply</button>
                            <a class="btn btn-outline-warning" href="{% url 'currency:rate_list' %}">
                                Reset
                            </a>
                        </div>
                    </form>
                </div>
            </div>
        </li>
        <li class="nav-item">
            <div class="container" style="border-style: inherit;">
                {# sort by select #}
                <button type="button" class="btn btn-outline-primary dropdown-toggle" data-toggle="dropdown">
                    Order by: <span class="badge badge-primary">{{ order_by_show }}</span>
                </button>
                <div class="dropdown-menu">
                    {% for key, value in order_choices.items %}
                        <a class="dropdown-item"
                           href="?page={{ page_obj.number }}&page_size={{ page_size }}&{{ filter_params }}&sort_by={{ key }}">
                            {{ value }}
                        </a>
                    {% endfor %}
                </div>
            </div>
        </li>
        <li class="nav-item">
            {% if request.user.is_superuser %}
            <a class="nav-link btn btn-outline-primary btn-sm" href="{% url 'currency:rate_create' %}">
                Create Rate
            </a>
            {% endif %}
        </li>
        <li class="nav-item">
            <a class="nav-link btn btn-outline-primary btn-sm" href="{% url 'currency:rate_download' %}">
                Download To CSV
            </a>
        </li>
    </ul>

    {% if rate_list %}
        <strong style="color: #007bff;">
            {% if filter_params_count > 0 %}
                Filtered: {{ filtered }} | Total: {{ total }}
            {% else %}
                No filter | Total: {{ total }} items
            {% endif %}
        </strong>
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Base Type</th>
                    <th>Type</th>
                    <th>Sale</th>
                    <th>Buy</th>
                    <th>Source</th>
                    <th>Created</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for rate in rate_list %}
                <tr>
                    <td>{{ rate.id }}</td>
                    <td>{{ rate.get_base_currency_type_display }}</td>
                    <td>{{ rate.get_currency_type_display }}</td>
                    <td>{{ rate.sale }}</td>
                    <td>{{ rate.buy }}</td>
                    <td>{{ rate.source.name }}</td>
                    <td>{{ rate.created|date:'Y-m-d H:i' }}</td>
                    <td>
                        <a href="{% url 'currency:rate_details' pk=rate.id %}">Details</a>
                        {% if request.user.is_superuser %}
                            <a href="{% url 'currency:rate_update' pk=rate.id %}">Edit</a>
                            <a href="{% url 'currency:rate_delete' pk=rate.id %}">Delete</a>
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

        {#Pagination#}
        {% include 'parts/pagination.html' %}


    {% else %}
        <p>Rate list is empty!</p>

    {% endif %}
{% endblock main_content %}

app/currency/templates/currency/source_details.html
{% extends 'currency/base.html' %}

{% block main_content %}
    {% if object %}
        <table class="table table-bordered table-hover">
            <thead>
                <tr class="table-active">
                    <th>Property</th>
                    <th>Value</th>
                </tr>
            </thead>
            <tbody>

                <tr>
                    <td>Source logo</td>
                    <td>
                        <img src="{{ object.logo.url }}" height="100">
                    </td>
                </tr>
                <tr>
                    <td>Source url</td>
                    <td>
                        <a href="{{ source.source_url }}" target="_blank">{{ source.source_url }}</a>
                    </td>
                </tr>
                <tr>
                    <td>Name</td>
                    <td>{{ object.name }}</td>
                </tr>
            </tbody>
        </table>
        <div>
            {% if request.user.is_superuser %}
                <a class="btn btn-success" href="{% url 'currency:source_update' pk=object.id %}">Edit</a>
                <a class="btn btn-danger" href="{% url 'currency:source_delete' pk=object.id %}">Delete</a>
            {% endif %}
        </div>
    {% else %}
        <p>Объект не найден!</p>p>
    {% endif %}
{% endblock main_content %}